sudo: required

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

services:
  - docker

install:
  - pip install -r requirements.txt

script: 
  - docker build -t test_build .
  - docker run test_build python3 /usr/src/fantasy_football_bot/setup.py test

env:
  - BOT_ID=916ccfd76a7fda25c74d09e1d5 LEAGUE_ID=164483
